name: lint

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    container:
      image: rocker/r-ver:latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        shell: Rscript {0}
        run: |
          install.packages("pak", repos = "https://cloud.r-project.org")
          pak::pkg_install("styler")

      - name: Show R session info
        shell: Rscript {0}
        run: sessionInfo()

      - name: Run styler
        shell: Rscript {0}
        run: |
          styler::style_pkg()

      - name: Check for style changes
        shell: bash
        run: |
          if ! git diff --quiet; then
            echo "================================="
            echo "Style issues detected"
            echo "================================="

            echo
            echo "Changed files:"
            git diff --name-only

            echo
            echo "Diff:"
            git --no-pager diff

            echo
            echo "Run locally:"
            echo "styler::style_pkg()"

            exit 1
          fi