jobs:
  lint:
    runs-on: ubuntu-latest

    container:
      image: rocker/r-ver:latest

    steps:
      - uses: actions/checkout@v5

      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y git

      - name: Install dependencies
        shell: Rscript {0}
        run: |
          install.packages("pak", repos = "https://cloud.r-project.org")
          pak::pkg_install("styler")

      - name: Run styler
        shell: Rscript {0}
        run: |
          styler::style_pkg()

      - name: Check formatting
        run: |
          git diff --name-only
          git --no-pager diff

          if ! git diff --quiet; then
            echo "Formatting issues detected"
            exit 1
          fi