name: R-CMD-check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    container: rocker/r-ver:latest

    steps:
      - uses: actions/checkout@v4

      - name: Install pak and dependencies
        run: |
          install.packages("pak", repos = "https://cloud.r-project.org")
          pak::local_install_deps(dependencies = TRUE)
          pak::pkg_install("rcmdcheck")
        shell: Rscript {0

      - name: Check
        run: |
          options(crayon.enabled = TRUE)
          rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran"), error_on = "warning", check_dir = "check")
        shell: Rscript {0}

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: R-CMD-check-results
          path: check/